name: Deploy all
run-name: Deploy all is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  Deploy:
    uses: ./.github/workflows/deploy.yml
    fail-fast: false
    strategy:
      matrix:
        region: [ cn, global ]
        service: [ api, document ]
        stage: [ staging, production ]
        exclude:
          - service: document
            stage: staging
    with:
      region: ${{ matrix.region }}
      stage: ${{ matrix.stage }}
      service: ${{ matrix.service }}
    secrets: inherit
